title: Allan Anderson's GitHub Pages
subtitle: A resource for students
author: Allan Anderson
email: aanderson@nait.ca
minima:
  date_format: "%b %-d, %Y"
github_username: allanNAIT
description: A collection of notes and resources for students.
show_excerpts: false # set to true to show excerpts on the homepage

header_pages:
 - anap1525/index.md
 - comp1017/index.md
 - cpsc1012/index.md
 #- dmit1508/index.md
 #- dmit1530/index.md
 #- phys1521/index.md
 #- dmit2018/index.md
 #- dmit2028/index.md
 - report-proofing.md
 - about.md

exclude:
  README.md
theme: minima

favicon: favicon.ico
