title: Allan's GitHub Pages
author: Allan Anderson
minima:
  date_format: "%b %-d, %Y"
  social_links:
    github: github.com/bandit412
description: A collection of notes and resources for my DMIT courses.
show_excerpts: false # set to true to show excerpts on the homepage

header_pages:
# - anap1525.md
 - comp1017.md
 - dmit1508.md
 - dmit1530.md
 - phys1521.md
 - about.md
theme: minima
